version: '3'

services:
  kafka1:
    image: 'lifsh/kafka'
    hostname: kafka1
    networks: 
      - zookeeper_default
    ports:
      - '9092:9092'
    volumes:
      - 'kafka1_data:/kafka-logs'
    environment:
      - BROKER_ID=1
      - ZK_SERVER=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_HOST=kafka1
      - KAFKA_PORT=9092
      - KAFKA_LOG_DIR=/kafka-logs
      - REPLICA_FACTOR=3
  kafka2:
    image: 'lifsh/kafka'
    hostname: kafka2
    networks: 
      - zookeeper_default
    ports:
      - '9093:9093'
    volumes:
      - 'kafka2_data:/kafka-logs'
    environment:
      - BROKER_ID=2
      - ZK_SERVER=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_HOST=kafka2
      - KAFKA_PORT=9093
      - KAFKA_LOG_DIR=/kafka-logs
      - REPLICA_FACTOR=3
  kafka3:
    image: 'lifsh/kafka'
    hostname: kafka3
    networks: 
      - zookeeper_default
    ports:
      - '9094:9094'
    volumes:
      - 'kafka3_data:/kafka-logs'
    environment:
      - BROKER_ID=3
      - ZK_SERVER=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_HOST=kafka3
      - KAFKA_PORT=9094
      - KAFKA_LOG_DIR=/kafka-logs
      - REPLICA_FACTOR=3
  kafka-ui:
    image: 'obsidiandynamics/kafdrop'
    networks: 
      - zookeeper_default
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092
    depends_on:
      - kafka1
 
volumes:
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local

networks:
  zookeeper_default:
    external: true
